### ISSUE TITLE
'action' is not defined  no-undef

### ISSUE THREAD

**Issue by elghali** [ritz078/react-fuzzy-search#10]
`<FuzzySearch
          ref={(node) => {this.search = node;}}
          list={list}
          keys={['title', 'label']}
          width={430}
          onSelect={action('selected')}
        />`
i'm not sure what i'm missing here but this code fails to compile with this error: 'action is not defined no-undef',
i'm not sure how to return the chosen item to the input, i tried replacing {action('selected')} with my own method 'handleSelected': 
`  handleSelected(event){
    this.setState({
      selected: event.title
    })
  }`
but i can't tell how to feed the state back to the input as there is no 'value' property for example

**Comment by ritz078** [comment]
Is the error still there ?

**Comment by elghali** [comment]
yes it is, i am using `onSelect={this.handleSelected}` which is my custom method, but i'm not sure if you released the last fix so it updates the value

**Comment by rcolepeterson** [comment]
Same error.
Using the example code.

**Comment by revengemiroz** [comment]
i am having the same issue any solution to it ?

**Comment by PatrickDesign** [comment]
>i can't tell how to feed the state back to the input as there is no 'value' property for example

`react-fuzzy` is currently an uncontrolled component. https://github.com/ritz078/react-fuzzy-search/issues/25#issuecomment-703833943

Here is an example `onSelect` method to retrieve the selected value for local state:

```
onSelect={(newSelectedItem) => {
  // Local state setter defined elsewhere
  setSelectedItem(newSelectedItem)
}}
```
