### ISSUE TITLE
npm start errors

### ISSUE THREAD

**Issue by elghali** [ritz078/react-fuzzy-search#13]
110467 verbose lifecycle react-fuzzy@0.4.0~prepublish: CWD: C:\Users\developer.CTServ\Desktop\React\tutorials\react-fuzzy-search
110468 silly lifecycle react-fuzzy@0.4.0~prepublish: Args: [ '/d /s /c', '. ./.scripts/prepublish.sh' ]
110469 silly lifecycle react-fuzzy@0.4.0~prepublish: Returned: code: 1  signal: null
110470 info lifecycle react-fuzzy@0.4.0~prepublish: Failed to exec prepublish script
110471 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
110472 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
110473 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
110473 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
110473 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
110473 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
110474 warn babel-loader@7.1.1 requires a peer of webpack@2 || 3 but none was installed.
110475 verbose If you need help, you may report this error at:
110475 verbose     <https://github.com/npm/npm/issues>
110476 verbose stack Error: react-fuzzy@0.4.0 prepublish: `. ./.scripts/prepublish.sh`
110476 verbose stack Exit status 1
110476 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
110476 verbose stack     at emitTwo (events.js:106:13)
110476 verbose stack     at EventEmitter.emit (events.js:194:7)
110476 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
110476 verbose stack     at emitTwo (events.js:106:13)
110476 verbose stack     at ChildProcess.emit (events.js:194:7)
110476 verbose stack     at maybeClose (internal/child_process.js:899:16)
110476 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
110477 verbose pkgid react-fuzzy@0.4.0
110478 verbose cwd C:\Users\developer.CTServ\Desktop\React\tutorials\react-fuzzy-search
110479 error Windows_NT 6.3.9600
110480 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
110481 error node v7.9.0
110482 error npm  v4.2.0
110483 error code ELIFECYCLE
110484 error errno 1
110485 error react-fuzzy@0.4.0 prepublish: `. ./.scripts/prepublish.sh`
110485 error Exit status 1
110486 error Failed at the react-fuzzy@0.4.0 prepublish script '. ./.scripts/prepublish.sh'.
110486 error Make sure you have the latest version of node.js and npm installed.
110486 error If you do, this is most likely a problem with the react-fuzzy package,
110486 error not with npm itself.
110486 error Tell the author that this fails on your system:
110486 error     . ./.scripts/prepublish.sh
110486 error You can get information on how to open an issue for this project with:
110486 error     npm bugs react-fuzzy
110486 error Or if that isn't available, you can get their info via:
110486 error     npm owner ls react-fuzzy
110486 error There is likely additional logging output above.
110487 verbose exit [ 1, true ]

**Comment by ritz078** [comment]
Actually there is no need for npm start. It can be removed.

**Comment by elghali** [comment]
but when i clone the repo locally, how can i start the app?

**Comment by ritz078** [comment]
run `yarn storybook` or `npm run storybook`

**Comment by elghali** [comment]
thank you it works
