### ISSUE TITLE
Is there a way to remove any styling at all?

### ISSUE THREAD

**Issue by tankorsmash** [ritz078/react-fuzzy-search#17]
The code uses a hardcoded `styles.searchBoxWrapper` for the input, and I'm looking to style the button completely myself (well, boostrap 4). Is there a way to either disable the styling or pass in the styles this'll use?

It seems like you can't change it, given how its a const but maybe I'm missing something.

**Comment by ritz078** [comment]
Currently there isn't but I plan to do it. It should be a very simple change.

**Comment by tankorsmash** [comment]
No worries, thanks for the plugin!

**Comment by PatrickDesign** [comment]
Workaround: https://github.com/ritz078/react-fuzzy-search/issues/42#issuecomment-702331793
