### ISSUE TITLE
show result based on type

### ISSUE THREAD

**Issue by ssageghi** [ritz078/react-fuzzy-search#18]
Hi
I have multiple models and I made a list from all of them and list object has a type attribute to separate them 
Is there a way to make fuzzy search to show 3 top results from every model 
and another question is the component always give me 9 result
Is there a way to get more or less result?
thanks for your amazing component

**Comment by PatrickDesign** [comment]
To answer part of your question, the `maxResults` prop allows you to specify your limit 😄.

**Comment by ssageghi** [comment]
@PatrickDesign thank u for quick answer dude  😄😄.😄..
