### ISSUE TITLE
Update options passthrough

### ISSUE THREAD

**Issue by sorahn** [ritz078/react-fuzzy-search#20]
Hello,

Currently the way you have the options set up is not great for future upgrades to Fuse since your options can quickly go out of date.  Example `include` is now `includeMatches`.

I'd be happy to write a pull request if anyone cares.

Do you plan on supporting this module (given PRs by other people) or should I just write my own stuff.

Thanks.

**Comment by ritz078** [comment]
you are welcome to create a PR. I will merge it if it is complete. The other opened PR is not complete and I never got time to complete it.
