### ISSUE TITLE
Feature - Title could be dynamic

### ISSUE THREAD

**Issue by ghost** [ritz078/react-fuzzy-search#22]
I can have objects where title is not the key to be displayed. We could personalize that:

{val.specialKey || val.title}

**Comment by lcarlesso** [comment]
I can make a PR if you prefer.

**Comment by ritz078** [comment]
PR is welcome.

**Comment by master-elodin** [comment]
PR created. Also fixes issue where dropdown is blank when `id` is given

**Comment by PatrickDesign** [comment]
This should be closed by https://github.com/ritz078/react-fuzzy-search/pull/43
