### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by bhumbash** [ritz078/react-fuzzy-search#42]
Is it possible to alter this component's style without changing values in the index.js? I see there was an issue talking about this a few years ago, has it been resolved? Thanks.

**Comment by PatrickDesign** [comment]
It's not ideal, but for the moment you can override using `!important`.

Example:
```
.react-fuzzy-search {
    width: 100% !important;

    div {
      box-shadow: none !important;
    }

    > div {
      padding: 0 !important;
    }

    input {
      border: 0 !important;
    }
  }
```
